ALTER TABLE chats ADD COLUMN IF NOT EXISTS avatar_data BYTEA;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS avatar_mime TEXT;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS avatar_updated_at BIGINT;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS avatar_key TEXT;
